# C:\dev\Captions_Formatter\Formatter_machine\config.yaml
# This version is synchronized with the refactored ISCE package.

# --- Algorithm Parameters ---
beam_width: 14

# --- Fallback Constraints ---
# These are used by the trainer if the learned constraints.json cannot be found.
constraints:
  min_block_duration_s: 1.0
  max_block_duration_s: 8.0
  line_length_soft_target: 37
  line_length_hard_limit: 42
  min_chars_for_single_word_block: 10

# --- Exceptions ---
allowed_single_word_proper_nouns:
  - "NASA"
  - "YouTube"

# --- Stylistic Sliders & Boosts ---
sliders:
  # Multipliers for learned statistical weights
  flow: 1.0       # Controls importance of general rhythm (pauses, punctuation).
  density: 2.0    # Controls importance of ideal reading speed (CPS).
  balance: 2.0    # Controls importance of line balance.

  # Leniency controls for dynamic penalties
  line_length_leniency: 1.0 # >1.0 allows longer lines to avoid bad breaks.
  orphan_leniency: 2.0      # >1.0 makes the penalty for orphans stronger.
  single_word_line_penalty: 12.0   # Strong penalty for orphaned or sub-minimal lines.
  extreme_balance_penalty: 6.0     # Penalty when one line dwarfs the other in character count.
  extreme_balance_threshold: 2.2   # Character ratio threshold before extreme balance penalty applies.

  # Additive boost for structural breaks (speaker changes, dashes, LLM hints)
  structure_boost: 18.0

# --- File Paths (relative to this config file's location) ---
paths:
  model_weights: "models/v1/model_weights.json"
  constraints: "models/v1/constraints.json"